import { Toaster } from "@/components/ui/sonner";
import ReactQueryProvider from "@/ReactQueryProvider/ReactQueryProvider";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { Marcellus, Paytone_One } from "next/font/google";
import "./[locale]/globals.css";

const CustomFont = Marcellus({
  variable: "--font-custom",
  subsets: ["latin"],
  weight: "400",
});

const LogoFont = Paytone_One({
  variable: "--font-logo",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: {
    default: "Next js Course",
    template: "%s | Next js Course",
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <body
        className={`${CustomFont.variable} ${LogoFont.variable} ${CustomFont.className} antialiased`}
      >
        {/* <ErrorWrapper> */}
        <NextIntlClientProvider>
          <ReactQueryProvider>
            <Toaster />
            {children}
          </ReactQueryProvider>
        </NextIntlClientProvider>
        {/* </ErrorWrapper> */}
      </body>
    </html>
  );
}
