import type { Metadata } from "next";
import { Marcellus } from "next/font/google";
import "./globals.css";
import { hasLocale } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";

const CustomFont = Marcellus({
  variable: "--font-custom",
  subsets: ["latin"],
  weight: "400",
})

export const metadata: Metadata = {
  title: {
    default: "Next js Course",
    template: "%s | Next js Course",
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang={locale}>
      <body className={`${CustomFont.className} antialiased`}>
        {/* <ErrorWrapper> */}
        {children}
        {/* </ErrorWrapper> */}
      </body>
    </html>
  );
}
